bbit_page_router:
    resource: .
    type: page_route
    requirements:
        uri: '^$|[^/]++'

bbit_pages:
    path:      /admin/pages
    defaults:  { _controller: BBITPageBundle:AdminPage:index }
bbit_pages_edit:
    path:      /admin/pages/{id}/edit
    defaults:  { _controller: BBITPageBundle:AdminPage:edit }


bbit_homepage:
    path:      /
    defaults:  { _controller: BBITPageBundle:Route:homePageRoute }
