<?php

namespace BBIT\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbstractPageRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class AbstractPageRepository extends EntityRepository
{
}
